#Dev: FebanHD
#SourceCode: https://github.com/FebbanHD123/MLGRush
#config-version: 1.5

#settings

#The databse-type (MySQL, SQLLite)
database: SQLLite

points.for_win: 10

#The queue-entity type (List of all entities: http://spigotjpwiki.github.io/org/bukkit/entity/EntityType.html)
queue_entity_type: ENDER_CRYSTAL

#The time in seconds when you cannot move
no_move_time: 1.5

#Blocks per Tick which will place
map_generation.spawningrate: 10

#The distance between the maps (in blocks) it should be more than your largest map width
paste.distance: 150

#messages

prefix: '&8[&cAdvancedMLGRush&8] &r'

nopermissions: '&cDazu hast du keine Rechte!'

queue_entity_name: '&5&lWarteschlange &8(&7Rechtsklick&8)'

messages.queue.enter: '&7Du hast die &5Warteschlange &7betreten.'
messages.queue.quit: '&7Du hast die &5Warteschlange &7verlassen.'
messages.map_selection_cancel: '&cDie Mapauswahl wurde abgebrochen!'
messages.round_win: '&7Du hast die Runde &agewonnen!'
messages.round_loose: '&7Du hast die Runde &cverloren!'
messages.round_cancel_playerquit: '&cDie Runde wurde abgebrochen, da dein Gegner die Runde verlassen hat.'
messages.map_creation.cancel: '&cDer Vorgang wurde abgebrochen, da dein Gegner den Server verlassen hat.'
messages.not_in_round: '&cDu bist bereits in keine Runde!'
messages.leave_round: '&7Du hast die Runde verlassen.'
messages.leave.usage: '&7Benutze &e/leave &7um die Runde zu verlassen.'

#%n% steht f√ºr eine neue linie in der Nachricht
messages.stats.command: '&7Stats von &e%player% %n%&7Kills: &e%kills% %n%&7Tode: &e%deaths%%n%&7K/D: &e%kd% %n%&7Spiele gwonnen: &e%wins% %n%&7Spiele verloren: &e%looses% %n%&7Betten abgebaut: &e%beds%'
messages.stats.loading: '&7Lade Stats...'
messages.stats.not_found: '&cDieser Spieler hat keine Stats.'

messages.inventorysorting.error: '&cEs ist ein Fehler beim Speichern deiner Sortierung aufgetreten. Achte darauf das alle Items im Inventar vorhanden sind!'
messages.inventorysorting.error_in_round: '&cDu darfst diesen Command aktuell nicht ausfueren.'
messages.inventorysorting.succesfully: '&7Deine Inventarsortierung wurde &agespeichert&7.'

messages.lobby.already_one_opponent: '&cDieser Spieler hat bereits einen Gegner!'
messages.lobby.challenged: '&7Du hast &a%player% &7herrausgefordert&7.'
messages.lobby.challenged_by_player: '&7Du wurdest von &a%player% &7herrausgefordert.'

items.stick: '&cStick'
items.challanger: '&5Herrausforderer &8(&7Spieler Schlagen&8)'

guiname.inventorysorting: '&eInventarsortierung'
guiname.mapchoosing: '&eWeale die Map'